version: '3'

services:
  api-doc-mongodb:
    image: ${DOCKER_REGISTRY-}apidocmongodb
    build:
      context: .
      dockerfile: api-doc-mongodb/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db-doc-mongodb 
  db-doc-mongodb:
    image: mongo:latest
    container_name: db-doc-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydevdb
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword


